plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.10.0'
}

group = 'io.github.agomezlucena'
version = '0.0.1-SNAPSHOT'
description = 'price-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = file("src/main/resources/openapi.yaml").toURI().toString()
    outputDir = layout.buildDirectory.dir("generated").get().asFile.absolutePath
    apiPackage = 'io.github.agomezlucena.prices.openapi.generated.api'
    modelPackage = 'io.github.agomezlucena.prices.openapi.generated.model'
    configOptions = [
            interfaceOnly       : 'true',
            useSpringBoot3      : 'true',
            useTags             : 'true',
            skipDefaultInterface: 'true',
            openApiNullable     : 'false'
    ]
}

sourceSets {
    main {
        java {
            srcDir "${layout.buildDirectory.asFile.get().absolutePath}/generated/src/main/java"
        }
    }
}

repositories {
    mavenCentral()
}

compileJava.dependsOn tasks.openApiGenerate

dependencies {
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'
    implementation 'org.springframework.boot:spring-boot-h2console'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

